// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDRRtZS-e0XG6K2Zwi7Tl_6lv1r2tI2M',
    appId: '1:588633880557:web:29195d89dcc479a5c0d9e4',
    messagingSenderId: '588633880557',
    projectId: 'collegeapp-f729b',
    authDomain: 'collegeapp-f729b.firebaseapp.com',
    storageBucket: 'collegeapp-f729b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3pnZEbtYsFeaaM3O_ALhzl5xZtI2cls',
    appId: '1:588633880557:android:16dc049a1b44d2c1c0d9e4',
    messagingSenderId: '588633880557',
    projectId: 'collegeapp-f729b',
    storageBucket: 'collegeapp-f729b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCej6aM5pfAQhUjHm20s7HvdkAio184_0o',
    appId: '1:588633880557:ios:9953ed41e0654ea0c0d9e4',
    messagingSenderId: '588633880557',
    projectId: 'collegeapp-f729b',
    storageBucket: 'collegeapp-f729b.firebasestorage.app',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCej6aM5pfAQhUjHm20s7HvdkAio184_0o',
    appId: '1:588633880557:ios:9953ed41e0654ea0c0d9e4',
    messagingSenderId: '588633880557',
    projectId: 'collegeapp-f729b',
    storageBucket: 'collegeapp-f729b.firebasestorage.app',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDRRtZS-e0XG6K2Zwi7Tl_6lv1r2tI2M',
    appId: '1:588633880557:web:e9bfea9faeb22dfec0d9e4',
    messagingSenderId: '588633880557',
    projectId: 'collegeapp-f729b',
    authDomain: 'collegeapp-f729b.firebaseapp.com',
    storageBucket: 'collegeapp-f729b.firebasestorage.app',
  );
}
